### ISSUE TITLE
Nomenclature

### ISSUE THREAD

**Issue by kareemkudus** [IMICSLab/pLGG_Predict_Status#1]
https://github.com/IMICSLab/pLGG_Predict_Status/blob/e2315710974d9d2e702cdaee612883b76714560a/main-radiomics.py#L245

I think maybe you should change how you are naming things here, it is a bit confusing, and doesn't match up with your write-up. "x_train" is really "x_development" which is divided into "x_train", and "x_validate" k times by grid search CV. "x_validate" is really "x_test_internal", or something like that.

**Comment by justin13601** [comment]
Yep great point, I'll make sure to change this
